# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - PlanningBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"
          include-prerelease: true

      - name: Build
        run: dotnet build .\api\API\api.sln -c Release -o ${{env.DOTNET_ROOT}}/artifacts

      - name: Unit tests
        run: dotnet test ${{env.DOTNET_ROOT}}/artifacts/Domain.Tests.dll ${{env.DOTNET_ROOT}}/artifacts/API.Unit.Tests.dll

      - name: Start SQL Server
        run: docker-compose -f docker-compose.db.yml up -d

      - name: Integration tests
        run: dotnet test ${{env.DOTNET_ROOT}}/artifacts/DB.Tests.dll ${{env.DOTNET_ROOT}}/artifacts/API.Integration.Tests.dll

      - name: dotnet publish
        run: dotnet publish .\api\API\API.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          path: ${{env.DOTNET_ROOT}}/myapp
          name: .net-app

  deploy:
    runs-on: ubuntu-latest
    needs: build-n-test
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "PlanningBackend"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B9A70394053246948A13B4BDE2A0AFD6 }}
          package: .
